### ISSUE TITLE
Bearing type in arms

### ISSUE THREAD

**Issue by chuismiguel** [momysnow/Momy-Desk-Robot#1]
Hello! I find your project super interesting and well done and I was looking forward to building your robot. I have seen in the step file that there is this piece

![image](https://github.com/momysnow/Momy-Desk-Robot/assets/78983070/9fc68e66-290f-48e1-a346-451981bb09f2)

Who i understand is a bearing, since the arm rotates on it. It appears as "cuscinetto" who translates as bearing. Which type is it?

Thanks a lot in advance!

**Comment by momysnow** [comment]
Hello, yes, it's a bearing. I forgot to translate the names in the STEP file as well. The bearings for the project are 6700ZZ, and I bought them on Amazon. Here is the link: [https://amzn.eu/d/4FSmGKP](https://amzn.eu/d/4FSmGKP). I looked for bearings that could work, but without delving too much into the specific features. If you find similar ones with the same dimensions, that's fine too.

> Hello! I find your project super interesting and well done and I was looking forward to building your robot. I have seen in the step file that there is this piece
> 
> ![image](https://private-user-images.githubusercontent.com/78983070/287527177-9fc68e66-290f-48e1-a346-451981bb09f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2Mjg0NjEsIm5iZiI6MTcwMTYyODE2MSwicGF0aCI6Ii83ODk4MzA3MC8yODc1MjcxNzctOWZjNjhlNjYtMjkwZi00OGUxLWEzNDYtNDUxOTgxYmIwOWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDE4MjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYTE4ZTY3ZDcxMGY5NGI3Njg4MzM2ZjFiODQ3NTMyYjFjZDNkODFiMTRkYzE4ZWI3MDE2ZGQ1YjNiZmY0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zzJf0U-az-FmIdIVVWwShg0CkhXcYpG1yuSET9TNK_g)
> 
> Who i understand is a bearing, since the arm rotates on it. It appears as "cuscinetto" who translates as bearing. Which type is it?
> 
> Thanks a lot in advance!
